name: Notify Slack on Push

on:
  push:
    branches:
      - "*" # Change this to your preferred branch

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_PR_CHANNEL_ID }} # Replace with your channel ID or use dynamic discovery

        run: |
          curl -X POST "https://slack.com/api/chat.postMessage" \
          -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{
            "channel": "'$SLACK_CHANNEL_ID'",
            "text": "A new push was made to branch: ${{ github.ref }}\nCommit: ${{ github.sha }}\nPushed by: ${{ github.actor }}",
            "attachments": [
              {
                "color": "#36a64f",
                "text": "Repository: ${{ github.repository }}\nCommit Message: ${{ github.event.head_commit.message }}"
              }
            ]
          }'
