name: Fly Deploy
on:
  push:
    branches:
      - main # change to main if needed
jobs:
  slack-notify:
    name: Slack-Notification
    needs: [deploy]
    if: always()
    uses: ./.github/workflows/slack.yml
    with:
      STATUS: "${{ needs.run-test.result }} ${{ needs.build-app-image.result }}"
    secrets:
      SLACK_PR_CHANNEL_ID: ${{ secrets.SLACK_PR_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
