name: Re-usable Slack Notification for PR Events

on:
  workflow_call:
    inputs:
      slack_channel_id:
        description: "Slack Channel ID"
        required: true
        type: string
      slack_bot_token:
        description: "Slack Bot Token"
        required: true
        type: string
      pr_action:
        description: "PR Action (opened, closed, etc.)"
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification for PR

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_PR_CHANNEL_ID }}
          PR_ACTION: ${{ inputs.pr_action }}

        run: |
          curl -X POST "https://slack.com/api/chat.postMessage" \
          -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{
            "channel": "'$SLACK_CHANNEL_ID'",
            "text": "A pull request has been $PR_ACTION in the repository: ${{ github.repository }}\nPR Title: ${{ github.event.pull_request.title }}\nBy: ${{ github.actor }}",
            "attachments": [
              {
                "color": "#36a64f",
                "text": "PR URL: ${{ github.event.pull_request.html_url }}\nAction: $PR_ACTION\nBranch: ${{ github.ref }}"
              }
            ]
          }'
